# See: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for the ns-tests-replicated-2 project

Parameters:
  Environment:
    Description: Engineering environment
    Type: String
  Platform:
    Description: Platform (e.g. talos)
    Type: String
    Default: talos
  Function:
    Description: Function (e.g. saas, bugcrowd)
    Type: String
    Default: lambda
  Component:
    Description: Component (e.g. nstestsreplicated2)
    Type: String
    Default: "nstestsreplicated2"

Globals:
  # See: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  Function:
    CodeUri: s3://serverless-231405699240/c8190c3f0bf04fe7955c6ded701d41edc792e8ef73ed0c2f00b49cca58a1dd4c  # DO NOT CHANGE; this is templated by `./build.sh`
    Handler: lambdex_handler.handler
    Runtime: python3.6
    Tags:
      Environment: !Ref Environment
      Platform: !Ref Platform
      Function: !Ref Function
      Component: !Ref Component

Mappings:
  EnvironmentMap:
    Prod:
      VPCID: vpc-885e8cef
      PublicSubnets:
        - subnet-d20a3def
        - subnet-ac80bbda
        - subnet-7cecb824
        - subnet-1ace8530
      PrivateSubnets:
        - subnet-df0a3de2
        - subnet-af80bbd9
        - subnet-7decb825
        - subnet-01ce852b
      SecuredSubnets:
        - subnet-dc0a3de1
        - subnet-a180bbd7
        - subnet-70ecb828
        - subnet-06ce852c
      LambdaFunctionRoleArn: arn:aws:iam::231405699240:role/prod-lexio-serverless-runtime
    NonProd:
      VPCID: vpc-885e8cef
      PublicSubnets:
        - subnet-b4083f89
        - subnet-2485be52
        - subnet-faeebaa2
        - subnet-92cc87b8
      PrivateSubnets:
        - subnet-b7083f8a
        - subnet-2785be51
        - subnet-ffeebaa7
        - subnet-91cc87bb
      SecuredSubnets:
        - subnet-ba083f87
        - subnet-2085be56
        - subnet-f2eebaaa
        - subnet-9ccc87b6
      LambdaFunctionRoleArn: arn:aws:iam::231405699240:role/nonprod-lexio-serverless-runtime

Conditions:
  Production: !Equals [!Ref Environment, prod]

Resources:
  # See: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub "Lexio Python function built with Pants (${Component})"
      FunctionName: !Sub "${Environment}-${Platform}-${Function}-${Component}"
      Timeout: 30
      MemorySize: 3008
      Role:
        !If
          - Production
          - !FindInMap [EnvironmentMap, Prod, LambdaFunctionRoleArn]
          - !FindInMap [EnvironmentMap, NonProd, LambdaFunctionRoleArn]
      VpcConfig:
        SecurityGroupIds:
          - !If
              - Production
              - !ImportValue prod-talos-database-securitygroup
              - !ImportValue integ-talos-database-securitygroup
        SubnetIds:
          !If
            - Production
            - !FindInMap [EnvironmentMap, Prod, PrivateSubnets]
            - !FindInMap [EnvironmentMap, NonProd, PrivateSubnets]
      Environment:
        Variables:
          Environment: !Ref Environment
          Platform: !Ref Platform
          Function: !Ref Function
          Component: !Ref Component

Outputs:
  LambdaFunction:
    Description: Lambda Function ARN
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-lambda-function-arn"
