python_library(
    dependencies=[
        "3rdparty/python:ansicolor",
        "3rdparty/python:behave",
        "3rdparty/python:coloredlogs",
        "3rdparty/python:jsonpath",
        "3rdparty/python:requests",
        "generic_behave/ns_behave/common",
        "generic_behave/ns_requests",
    ],
    sources=["ns_behave/**/*"],
    tags={"code", "lib", "python"},
)
