python_library(
    dependencies=[
        "3rdparty/python:ansicolor",
        "3rdparty/python:behave",
        "3rdparty/python:coloredlogs",
        "3rdparty/python:jsonpath",
        "3rdparty/python:requests",
        "src/generic_behave/lib/test_utils/common/src",
        "src/generic_behave/lib/test_utils/behave/src",
        "src/generic_behave/lib/test_utils/launchdarkly/src",
        "src/generic_behave/lib/test_utils/requests/src",
    ],
    sources=globs("ns_behave/**/*"),
    tags={"code", "lib", "python"},
)
