python_library(
    dependencies=[
        "3rdparty/python:ansicolor",
        "3rdparty/python:behave",
        "3rdparty/python:coloredlogs",
        "3rdparty/python:jsonpath",
        "3rdparty/python:requests",
        "test_utils/requests/src",
    ],
    sources=globs("ns_behave/**/*"),
    tags={".", "code", "python"},
)
