python_library(
    dependencies=[
        "3rdparty/python:ansicolor",
        "3rdparty/python:behave",
        "3rdparty/python:boto3",
        "3rdparty/python:requests",
        "test_utils/behave/src",
    ],
    sources=globs("ns_tests_replicated/**/*"),
    tags={".", "code", "python"},
)
