# See: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for the {{ cookiecutter.project_name }} ROFL Lambda Function

Parameters:
  Component:
    Description: Component that identifies the SAM application
    Type: String
    Default: "{{ cookiecutter.project_name }}"
  Environment:
    Description: Engineering environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - integ
      - prod
    ConstraintDescription: must be a valid engineering environment
  Platform:
    Description: Platform (e.g. talos)
    Type: String
    Default: talos
  Function:
    Description: Function (e.g. saas, bugcrowd)
    Type: String
    Default: saas
  LambdaFunctionRoleArn:
    Description: ARN of the IAM role to use for all Lambda Functions
    Type: String
    Default: arn:aws:iam::231405699240:role/nonprod-lexio-serverless-runtime

Globals:
  # See: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  Function:
    CodeUri: package/
    Handler: src/handler.handler
    Runtime: nodejs8.10
    # Default function timeout is 5 minutes. This should take into consideration the
    # HTTP retry configuration defined in the rofl.yml file (i.e. this number needs to
    # be greater than to total retry time).
    Timeout: 300
    Tags:
      Environment: !Ref Environment
      Platform: !Ref Platform
      Function: !Ref Function

Mappings:
  EnvironmentMap:
    TalosProd:
      LambdaFunctionRoleArn: arn:aws:iam::231405699240:role/prod-lexio-serverless-runtime
    TalosNonProd:
      LambdaFunctionRoleArn: arn:aws:iam::231405699240:role/nonprod-lexio-serverless-runtime

Conditions:
  Production:
    Fn::Equals: [!Ref Environment, prod]

Resources:
  # See: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  ROFLFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description:
        !Join
          - " "
          - - ROFL function for
            - !Ref Component
      FunctionName:
        !Join
          - "-"
          - - !Ref Environment
            - !Ref Platform
            - !Ref Function
            - !Ref Component
      Role:
        Fn::If:
          - Production
          - !FindInMap [EnvironmentMap, TalosProd, LambdaFunctionRoleArn]
          - !FindInMap [EnvironmentMap, TalosNonProd, LambdaFunctionRoleArn]
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt ROFLDeadLetterQueue.Arn
      # The maximum of concurrent executions you want to reserve for the function.
      # ReservedConcurrentExecutions: 5

  # This queue holds event payloads that the ROFLFunction failed to process
  ROFLDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        !Join
          - "-"
          - - !Ref Environment
            - !Ref Platform
            - !Ref Function
            - !Ref Component
            - dlq
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Platform
          Value: !Ref Platform
        - Key: Function
          Value: !Ref Function

  ROFLDeadLetterQueueAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
        !Join
          - "-"
          - - !Ref Environment
            - !Ref Platform
            - !Ref Function
            - !Ref Component
            - dlq-alarm
      AlarmDescription: >
        Alarm if the queue contains any messages after 15 minutes. This means that there
        are events that we failed to process even after retries.
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        -
          Name: QueueName
          Value:
            Fn::GetAtt:
              - ROFLDeadLetterQueue
              - QueueName
      Statistic: Sum
      Unit: Count
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      EvaluationPeriods: 3
      Period: 300
      TreatMissingData: ignore
      ActionsEnabled: false
      # TODO(QPT-22479): add an environment condition
      # ActionsEnabled:
      #   Fn::If:
      #     - Production
      #     - true
      #     - false
      # TODO(QPT-22479): get this alarm as a parameter or pulled from another stack
      # AlarmActions:
      #   - !Ref AlarmNotificationTopic
      #   - Fn::ImportValue: ProdTalosCloudwatchAlarmTopicArn-V1
      # OKActions:
      #   - Fn::ImportValue: ProdTalosCloudwatchAlarmTopicArn-V1
      

Outputs:
  ROFLFunction:
    Description: "ROFL Lambda Function ARN"
    Value: !GetAtt ROFLFunction.Arn
  ROFLDeadLetterQueue:
    Description: "ROFL Lambda Function Dead Letter Queue ARN"
    Value: !GetAtt ROFLDeadLetterQueue.Arn
