python_library(
    dependencies=[
        "3rdparty/python:ansicolor",
        "3rdparty/python:behave",
        "3rdparty/python:boto3",
        "3rdparty/python:coloredlogs",
        "3rdparty/python:jsonpath",
        "3rdparty/python:requests",
        "3rdparty/python:selenium",
    ],
    sources=["**/*"],
    tags={".", "code", "python"},
)
